# Array what I leared

In [ ]:
# 데이터의 행열 찾기
def shape(data):
	row = len(data[0])
	column = len(data)
	return row, column


subwayData = []
with open('../data/seoul_subway/seoul_subway.csv',\
	mode='r', encoding='utf-8') as f:
	for line in f.readlines():
		subwayData.append(line.split(','))

shape(subwayData)

(8, 616)

In [ ]:
import numpy as np


# subwayData의 행열바꾸기  
subwayData2 = np.array(subwayData).T

numpy의 T로 바꾸면 나오는 dtype='<U16'은 'np.unicode_' 16을 뜻한다.  

예시를 위해 만든 data를 보면 np.dtype()은 python에서 클래스 만드는 것과 같다. dtype='object'를 하지 않으면 warning이 뜨는데 np.array로 ndarray 개체를 만들때 예시처럼 리스트 안에 튜플 또는 리스트를 중첩해서 쓰는 기능은 사라진다는 내용이다. 이것을 하려면 대신 dtype='object'로 ndarray를 만들라는 것.

In [ ]:
# np.float64 뒤의 (2,)는 float data 2개 받겠다는 의미
data = np.dtype([('name', np.unicode_, 16), ('grade', np.float64, (2,))])
print(data['name'])
print(data['grade'])
print()

# x = np.array([('Scalar', (8.0, 9.3)), ('Vector', (9.8, 8.7))])
x = np.array([('Scalar', (8.0, 9.3)), ('Vector', (9.8, 8.7))], dtype='object')
print(x[0])
# x[0]['grade']  # numpy.org 예제와는 다르게 slice/indices 안된다
print(type(x[0]))

<U16
('<f8', (2,))

['Scalar' (8.0, 9.3)]
<class 'numpy.ndarray'>


C:\Users\lh\AppData\Local\Temp\ipykernel_14684\1289372564.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([('Scalar', (8.0, 9.3)), ('Vector', (9.8, 8.7))])


In [ ]:
i = 0
j = 0

# 2행 3열 만들기(1)
arrays = [[[0],[1],[2]], [[3],[4],[5]]]
for arr in arrays:
	print(arr)
print()

# 2행 3열 만들기(2)
arrays2 = [[],[]]
for i in range(2):
	for j in range(3):
		arrays2[i].append(i+j)
print(*arrays2, sep='\n')
print()

# 2행 3열 데이터를 3행 2열로 바꾸기
arrays3 = [[[], []],[[], []],[[], []]]
for i in range(3):
	for j in range(2):
		arrays3[i][j] = arrays2[j][i]
print(*arrays3, sep='\n')

[[0], [1], [2]]
[[3], [4], [5]]

[0, 1, 2]
[1, 2, 3]

[0, 1]
[1, 2]
[2, 3]


numpy 기능으로 행렬을 바꾸려면 list로 생성된 개체를 nparray 타입으로 변경해줘야 한다

In [ ]:
import numpy as np


arrays2_2 = np.array(arrays2)
arrays2_2.T

array([[0, 1],
       [1, 2],
       [2, 3]])

In [ ]:
import numpy as np


# int32 type, 초기값 1로 1행 5열
arr = np.ones(5, dtype='i')
print(arr)
print()

# 2행 3열 생성
arr2 = np.ones((2, 3), dtype='i')
print(arr2)
print()

# 초기값 0으로 3행 5열 생성
print(np.zeros((3, 5)))
print()

# empty로 하면 아무 값으로 생성
print(np.empty((3, 4)))
print()

# tuple X, scalar value only
# same as list(range(3))
print(np.arange(3))


[1 1 1 1 1]

[[1 1 1]
 [1 1 1]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1.37303950e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.16709769e-312 1.08646229e-071 2.85282351e-056 2.74272643e-057]
 [9.35446102e-067 2.85332716e-056 4.35519621e-061 9.59052900e-043]]

[0 1 2]


In [ ]:
# list(range)로도 만들 수 있지만 nparray 개체로 생성하려면
nparray1 = np.array([[5, 6, 7], [8, 9, 10]], dtype='i')
print('nparray1 type =', type(nparray1))
print('nparray1 shape =', nparray1.shape)
print('nparray1 size =', nparray1.size)

# print 했을때와 안했을떄의 차이
print(nparray1)
nparray1

nparray1 type = <class 'numpy.ndarray'>
nparray1 shape = (2, 3)
nparray1 size = 6
[[ 5  6  7]
 [ 8  9 10]]


array([[ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)

numpy로는 nparray 개체일때 행열이 같으면 명시적으로 반복문을 쓰지 않고 연산이 가능한데 기능은 반복문으로 구현을 했으나 코드에 for문을 적지 않아도 되는 방법이다. 

In [ ]:
x = np.array([[1, 2], [3, 4]])
2 * x

array([[2, 4],
       [6, 8]])

In [ ]:
# -1은 알아서 셋팅하는것을 의미
x.reshape(1, -1) # 행을 1개, 열을 알아서

array([[1, 2, 3, 4]])

In [ ]:
# 행은 알아서, 컬럼(열)은 1개
x.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
y = np.arange(6)
y

array([0, 1, 2, 3, 4, 5])

In [ ]:
y.reshape(2, -1)

[[0 1 2]
 [3 4 5]]


In [ ]:
x = np.arange(1, 11)
y = np.arange(11, 21)
z = np.zeros_like(x)

print(f'x.size: {x.size}, x.shape: {x.shape}, x[:5]: {x[:5]}')
print(f'y.size: {x.size}, y.shape: {y.shape}, y[:5]: {y[:5]}')
print(f'z.size: {z.size}, z.shape: {z.shape}, z[:5]: {z[:5]}')

# for i in range(10): z[i] = x[i] + y[i]
z = x + y
print(f'z.size: {z.size}, z.shape: {z.shape}, z[:5]: {z[:5]}')

xy = x==y
print(xy)

xy2 = x<y
print(xy2)

x.size: 10, x.shape: (10,), x[:5]: [1 2 3 4 5]
y.size: 10, y.shape: (10,), y[:5]: [11 12 13 14 15]
z.size: 10, z.shape: (10,), z[:5]: [0 0 0 0 0]
z.size: 10, z.shape: (10,), z[:5]: [12 14 16 18 20]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]


In [ ]:
x = np.linspace(5, 25, 3, dtype='i')
y = np.linspace(3, 15, 3, dtype='i')

print(x, y, sep='\n')
print(np.all(x==y))
print(np.any(x>=y))  # 15가 크거나 같다는 조건문에서만 True
print(np.any(x==y))  # 15가 같다는 조건문에는 False로 나옴

[ 5 15 25]
[ 3  9 15]
False
True
False


In [ ]:
# x, y 행렬의 모든값을 곱하려면
print(np.dot(x, y))
print(np.matmul(x, y))
print(x@y)

525
525
525


b처럼 int 타입으로 생성된 nparray가 있으면 take()나 a[b]처럼 a의 index로 사용할 수 있다. 다만 a의 갯수가 4개라면 b의 int type 숫자들도 a의 인덱스 번호 범위 안이어야 한다. 예를 들어 a에 5번째 요소가 없는데 b에 4가 들어있으면 범위 오류로 a[b] 또는 a.take(b)가 되지 않는다.

In [ ]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 3, 1], int)

# b를 인덱스로 사용하여 a의 0, 3, 1번째 값을 b의 순서대로 가져옴
print(a[b])
# a.take(b)

# 전체 요소의 최소값 위치(인덱스) 찾기
print(a.argmin())

# 첫번째 값부터 누적합
print(a.cumsum())

# 첫번째 값부터 누적곱
print(a.cumprod())

[2. 8. 4.]
0
[ 2.  6. 12. 20.]
[  2.   8.  48. 384.]
